format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fill\
$vcsh\
$shlvl\
$time\
$cmd_duration\
$jobs\
$line_break\
$custom\
$username@$hostname \
$status\
$character\
"""
right_format = """
"""
add_newline = false

[time]
disabled = false
format = "[TIME=](dimmed)[$time]($style) "
time_format = "%Y-%m-%d@%H:%M:%S"
style = "bold purple"
[cmd_duration]
disabled = false
min_time = 1
format = "[LAST_DUR=](dimmed)[$duration]($style) "
style = "bold purple"
[jobs]
symbol_threshold = 1
number_threshold = 1
format = "[JOBS=](dimmed)[$number]($style) "
style = "bold purple"
[shlvl]
disabled = false
threshold = 0
format = "[SHLVL=](dimmed)[$shlvl]($style) "
style = "bold purple"

[status]
disabled = false
pipestatus = true
map_symbol = false
recognize_signal_code = true
format = "[\\[$signal_name$symbol$status\\]]($style)"
pipestatus_format = "$pipestatus â†¦ [\\[$signal_name$symbol$status\\]]($style)"
pipestatus_separator = "|"
style = "blue"
symbol = "[ð„‚](bold red)"
success_symbol = "[ðŸ—¸](bold green)"


[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style)"
style = "bold dimmed #00b33c"
[username]
disabled = false
show_always = true
format = "[$user]($style)"
style_root = "bold red"
style_user = "bold yellow"
[directory]
truncate_to_repo = false
[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

[fill]
symbol = " "

